//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V3EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int RegistrationID { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
        public int AdultQty { get; set; }
        public Nullable<int> ChildQty { get; set; }
    
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
